Document: inflash
Title: Debian inflash Manual
Author: <insert document author here>
Abstract: This manual describes what inflash is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/inflash/inflash.sgml.gz

Format: postscript
Files: /usr/share/doc/inflash/inflash.ps.gz

Format: text
Files: /usr/share/doc/inflash/inflash.text.gz

Format: HTML
Index: /usr/share/doc/inflash/html/index.html
Files: /usr/share/doc/inflash/html/*.html
