/*
 * head.S
 *
 * Entry point of the firmware.
 * The firmware code are executed in the ICache.
 *
 * (C) Copyright 2009
 * Author: Xiangfu Liu <xiangfu@qi-hardware.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 3 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA  02110-1301, USA
 */

	.text

	.extern c_main

	.globl _start
	.set noreorder
_start:
	b	real_start
	nop
	.word	0x0 /* address: 0x80002008 */
	.word	0x0
	.word	0x0
	.word	0x0
	.word	0x0
	.word	0x0
	.word	0x0
	.word	0x0
	/* reserve 8 words for args
	 * this is must big then sizeof(sturct fw_args)
	 */
real_start:		
	/*
	 * setup stack, jump to C code
	 */
	la	$29, 0x80004000	/* sp */
	j	c_main
	nop

	.set reorder
